# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: smartshop-secrets
  namespace: smartshop
type: Opaque
stringData:
  GOOGLE_API_KEY: "AIzaSyBFkgAITVySPg_1aTYp7DHof1APmoiwPds"
  PROJECT_ID: "smart-shop-ai-496616"
  BQ_DATASET: "smartshop"
  BQ_LOCATION: "US"
  EMBEDDING_MODEL: "all-MiniLM-L6-v2"
  GOOGLE_GENAI_USE_VERTEXAI: "0"